# Generated by Django 2.2.5 on 2019-10-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('prodcut_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('product_stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('product_description', models.CharField(default='Null', max_length=300)),
                ('cart', models.CharField(default='0', max_length=1)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ID', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
            ],
            options={
                'unique_together': {('transaction_ID', 'product_ID')},
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(blank=True, max_length=200)),
                ('transaction_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.transaction')),
            ],
        ),
    ]
