# Generated by Django 2.2.5 on 2019-10-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191015_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagesrc',
        ),
    ]
