# Generated by Django 2.2.5 on 2019-10-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20191015_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_name',
            new_name='product_name',
        ),
    ]
