# Generated by Django 2.2.5 on 2019-10-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_product_imagesrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagesrc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
