# Generated by Django 2.2.5 on 2019-10-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20191015_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagesrc',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
